# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180722_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='bookface', verbose_name='图书'),
        ),
    ]
